/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const configExternalContracts = {
  devnet: {
    // No external contracts configured
  },
} as const;

export default configExternalContracts;
